# basic configuration
baseurl: /python-course
markdown: redcarpet
permalink: /:categories/:title/


ga_tracking_code: ''
p2pu_ga_tracking_code: ''

# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"

prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

# Set some personal styles and logo for your course
# this is a hex value http://www.w3schools.com/tags/ref_colorpicker.asp
jumbotron_color: "#FFFFFF"
jumbotron_background_image: "mooc-e.jpg"
jumbotron_image: "python-logo.png"
